[package]
name = "cartesi-dave-contracts"

version = "0.1.0"

authors = [
  "Gabriel Coutinho de Paula <gcdepaula@protonmail.io>",
  "Stephen Chen <stephenx747@gmail.com>",
]
description = "Cartesi Dave contract bindings"
edition = "2021"
homepage = "https://github.com/cartesi/dave"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/cartesi/dave"

[dependencies]
alloy = { version = "0.2.1", features = ["sol-types", "contract"] }
serde = "1"

