name = 'cartesi-dave-consensus-prod'
version = '2.0.0'
description = 'Cartesi Dave Consensus (prod)'

[var.Settings]
initialHash = "<%= zeroHash %>"
salt = "<%= zeroHash %>"

[pull.daveAppFactory]
source = "cartesi-dave-app-factory:2.0.0@main"

[invoke.newDaveApp]
target = "daveAppFactory.DaveAppFactory"
func = "newDaveApp(bytes32,bytes32)"
args = [
    "<%= settings.initialHash %>",
    "<%= settings.salt %>",
]
factory.ApplicationInstance.artifact = "Application"
factory.ApplicationInstance.event = "DaveAppCreated"
factory.ApplicationInstance.arg = 0
factory.DaveConsensusInstance.artifact = "DaveConsensus"
factory.DaveConsensusInstance.event = "DaveAppCreated"
factory.DaveConsensusInstance.arg = 1
