name = 'cartesi-dave-consensus-dev'
version = '2.0.0'
description = 'Cartesi Dave Consensus (dev)'

[var.Settings]
initialHash = "<%= zeroHash %>"
salt = "<%= zeroHash %>"

[pull.prtContracts]
source = "cartesi-prt-multilevel:2.0.0@main"

[deploy.InputBox]
artifact = "InputBox"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"

[deploy.ApplicationFactory]
artifact = "ApplicationFactory"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"

[deploy.DaveAppFactory]
artifact = "DaveAppFactory"
args = [
  "<%= InputBox.address %>",
  "<%= ApplicationFactory.address %>",
  "<%= prtContracts.MultiLevelTournamentFactory.address %>",
]
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"

[deploy.DaveAppAddressCalculator]
artifact = "DaveAppAddressCalculator"
args = ["<%= DaveAppFactory.address %>"]
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"

[invoke.calculateDaveAppAddress]
target = "DaveAppAddressCalculator"
func = "calculateDaveAppAddress(bytes32,bytes32)"
args = [
    "<%= settings.initialHash %>",
    "<%= settings.salt %>",
]
factory.ApplicationInstance.artifact = "IApplication"
factory.ApplicationInstance.event = "AddressCalculation"
factory.ApplicationInstance.arg = 2

[invoke.newDaveApp]
target = "DaveAppFactory"
func = "newDaveApp(bytes32,bytes32)"
args = [
    "<%= settings.initialHash %>",
    "<%= settings.salt %>",
]
factory.DaveConsensusInstance.artifact = "IDaveConsensus"
factory.DaveConsensusInstance.event = "DaveAppCreated"
factory.DaveConsensusInstance.arg = 1
depends = ["invoke.addInput"]

[invoke.addInput]
target = "InputBox"
func = "addInput"
args = [
    "<%= contracts.ApplicationInstance.address %>",
    "<%= stringToHex('Hello, world!') %>",
]
var.firstInput.event = "InputAdded"
var.firstInput.arg = 2
