[workspace]
resolver = "2"
members = [
  # Solidity bindings
  "cartesi-rollups/contracts/bindings-rs",
  "prt/contracts/bindings-rs",

  # rollups-node
  "cartesi-rollups/node",

  # machine bindings
  "machine/rust-bindings/cartesi-machine",
  "machine/rust-bindings/cartesi-machine-sys",
]

[workspace.package]
version = "2.0.0"

authors = [
  "Gabriel Coutinho de Paula <gcdepaula@protonmail.com>",
  "Stephen Chen <stephenx747@gmail.com>",
]
description = "A Cartesi validator reference implementation"
edition = "2024"
homepage = "https://github.com/cartesi/dave"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/cartesi/dave"

[workspace.dependencies]

## Workspace crates

# machine bindings
cartesi-machine = { path = "machine/rust-bindings/cartesi-machine" }

# solidity bindings
cartesi-dave-contracts = { path = "cartesi-rollups/contracts/bindings-rs" }
cartesi-prt-contracts = { path = "prt/contracts/bindings-rs" }

# rollups-node




## Dependencies

# cartesi
cartesi-rollups-contracts = "=3.0.0-alpha.10"

# eth
alloy = { version = "2.0", features = [
  "contract",
  "network",
  "reqwest",
  "signer-local",
  "signers",
  "sol-types",
] }
alloy-transport = { version = "2.0", features = ["throttle"] }
alloy-chains = { version = "0.2" }
reqwest = { version = "0.13", features = ["http2"] }
ruint = "1.12"
tiny-keccak = { version = "2.0", features = ["keccak"] }


# error handling
anyhow = "1.0"
thiserror = "2.0"

# async
async-recursion = "1"
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }

# sqlite
lazy_static = "1.4"
rusqlite = { version = "0.31.0", features = ["bundled", "functions"] }

clap = { version = "4.5", features = ["derive", "env"] }
hex = "0.4"
log = "0.4"
