name = 'cartesi-prt-multilevel-dev'
version = '2.0.0'
description = 'Cartesi PRT contracts (dev)'

[pull.prtContracts]
source = "cartesi-prt-multilevel:2.0.0@main"

[var.Settings]
initialHash = "<%= zeroHash %>"
dataProvider = "<%= zeroAddress %>"

[invoke.deployment]
target = "prtContracts.MultiLevelTournamentFactory"
func = "instantiate"
args = [
    "<%= settings.initialHash %>",
    "<%= settings.dataProvider %>",
]
factory.TopTournamentInstance.abiOf = ["prtContracts.TopTournament"]
factory.TopTournamentInstance.event = "tournamentCreated"
factory.TopTournamentInstance.arg = 0
