BINDINGS_DIR := "./bindings-rs/src/contract"
SRC_DIR := "."
BINDINGS_FILTER := "^[^I].+TournamentFactory|LeafTournament|RootTournament|^Tournament$"

export PRIVATE_KEY := "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
ANVIL_ENDPOINT := "http://127.0.0.1:8545"
ANVIL_CHAIN_ID := "31337"

default: build

build: build-smart-contracts bind
clean: clean-smart-contracts clean-bindings

build-smart-contracts:
    forge build

test:
    forge test --no-match-contract ".*FfiTest"
    forge test --match-contract ".*FfiTest" --no-match-test ".*Fuzzy" --ffi

test-fuzzy:
    forge test --match-contract ".*FfiTest" --match-test ".*Fuzzy" --ffi

clean-smart-contracts:
    forge clean

fmt:
    forge fmt

check-fmt:
    forge fmt --check

clean-bindings:
    rm -rf {{BINDINGS_DIR}}

bind: clean-bindings
    forge bind --alloy --select "{{BINDINGS_FILTER}}" \
    --module --bindings-path {{BINDINGS_DIR}} \
    --root {{SRC_DIR}}

deploy-dev INITIAL_HASH:
    forge script \
        script/TopTournament.s.sol \
        --fork-url {{ANVIL_ENDPOINT}} \
        --broadcast \
        --non-interactive \
        --sig 'run(bytes32)' \
        '{{INITIAL_HASH}}' \
        -vvvv 2>&1
