#!/usr/bin/env bash

set -euo pipefail

cd "${BASH_SOURCE%/*}/../../.."

# Get the address of a contract deployed to mainnet.
# Arguments:
# - A contract name
# Returns:
# - The address of the contract deployed to devnet.
get_devnet_deployment_address() {
    [[ $# -ge 1 ]] || \
        (>&2 echo "Expected 1 argument, but got $#." && exit 1)

    local contract_name="$1"

    [[ "$contract_name" =~ ^[a-zA-Z_$][a-zA-Z0-9_$]*$ ]] ||
        (>&2 echo "$contract_name is not a valid contract name." && exit 1)

    jq -r .address "cartesi-rollups/contracts/deployments/31337/${contract_name}.json"
}

ERC20_PORTAL_ADDRESS=$(get_devnet_deployment_address ERC20Portal)
ERC20_WITHDRAWAL_ADDRESS='0x70997970C51812dc3A010C7d01b50e0d17dc79C8'
ERC20_TOKEN_ADDRESS=$(get_devnet_deployment_address TestFungibleToken)

# Converts an Ethereum address as a C-style byte array.
# Arguments:
# - An Ethereum address
# Returns:
# - Address as C-style byte array.
to_c_array() {
    [[ $# -ge 1 ]] || \
        (>&2 echo "Expected 1 argument, but got $#." && exit 1)

    local address="$1"

    # Validate the address format
    [[ "$address" =~ ^0x[0-9a-fA-F]{40}$ ]] || \
        (>&2 echo "$address is not a valid Ethereum address." && exit 1)

    # Remove the '0x' prefix
    local hex_string="${address:2}"

    # Convert to comma-separated bytes
    local result=""
    for ((i=0; i<${#hex_string}; i+=2)); do
        local byte="${hex_string:i:2}"
        if [[ -n "$result" ]]; then
            result="${result},0x${byte}"
        else
            result="0x${byte}"
        fi
    done

    echo "{$result}"
}

echo '// Copyright Cartesi and individual authors (see AUTHORS)'
echo '// SPDX-License-Identifier: Apache-2.0 (see LICENSE)'
echo
echo "// This file was generated by ${BASH_SOURCE}"
echo
echo '#ifndef HONEYPOT_CONFIG_H'
echo '#define HONEYPOT_CONFIG_H'
echo
echo "// $ERC20_PORTAL_ADDRESS"
echo "#define CONFIG_ERC20_PORTAL_ADDRESS     $(to_c_array "$ERC20_PORTAL_ADDRESS")"
echo "// $ERC20_WITHDRAWAL_ADDRESS"
echo "#define CONFIG_ERC20_WITHDRAWAL_ADDRESS $(to_c_array "$ERC20_WITHDRAWAL_ADDRESS")"
echo "// $ERC20_TOKEN_ADDRESS"
echo "#define CONFIG_ERC20_TOKEN_ADDRESS      $(to_c_array "$ERC20_TOKEN_ADDRESS")"
echo
echo '#endif // HONEYPOT_CONFIG_H'
