FROM cartesi/machine-emulator:0.17.0

USER 0
RUN apt-get -y update && \
    apt-get -y install build-essential clang curl git libssl-dev pkg-config wget

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

COPY --from=ethereum/solc:0.8.23 /usr/bin/solc /usr/bin/solc
RUN chmod u+x /usr/bin/solc

WORKDIR /app

RUN wget https://github.com/cartesi/image-kernel/releases/download/v0.20.0/linux-6.5.13-ctsi-1-v0.20.0.bin \
    -O ./linux.bin
RUN wget https://github.com/cartesi/machine-emulator-tools/releases/download/v0.15.0/rootfs-tools-v0.15.0.ext2 \
    -O ./rootfs.ext2

RUN cartesi-machine --ram-image=./linux.bin \
    --flash-drive=label:root,filename:./rootfs.ext2 \
    --no-rollback --store=./echo \
    -- "ioctl-echo-loop --vouchers=1 --notices=1 --reports=1 --verbose=1"

# copy dependencies
COPY ./machine /app/machine
COPY ./common-rs /app/common-rs
COPY ./machine-emulator-sdk /app/machine-emulator-sdk
COPY ./prt /app/prt

# copy rollups-node application
COPY ./rollups-node /app/rollups-node
COPY ./.git /app/.git

WORKDIR /app/rollups-node

ENTRYPOINT ["./rollups-test-entrypoint.sh"]
