//! Defines the [struct@Hash] type.

use std::fmt::Display;

use cartesi_machine_sys::cm_hash;

/// Digest generated by a hash function.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Hash(cm_hash);

impl Display for Hash {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "0x{}", hex::encode(self.0))
    }
}

impl Hash {
    pub fn as_ptr(&self) -> *const cm_hash {
        &self.0
    }

    /// Create a new hash from a byte array.
    pub fn new(hash: [u8; 32]) -> Self {
        Self(hash)
    }

    /// Get the byte array representation of this hash.
    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}