[package]
name = "cartesi-prt-compute"
version = { workspace = true }

authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license-file = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[dependencies]
cartesi-prt-core = { path = "../core" }
alloy = { version = "0.2.1", features = ["sol-types"] }
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
env_logger = "0.10"
