ECHO_DIR := "../../../test/programs/echo"
HONEYPOT_DIR := "../../../test/programs/honeypot"

# TODO each program should get its own, from its own dir.
APP := "0x0000000000000000000000000000000000000000"
WEB3_PRIVATE_KEY := "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
MAX_EPOCH := "1"

# run PRT rollups test
test MACH_PATH:
  rm -rf _state
  WEB3_PRIVATE_KEY={{WEB3_PRIVATE_KEY}} \
  APP={{APP}} \
  MACHINE_PATH={{MACH_PATH}} \
  MAX_EPOCH={{MAX_EPOCH}} lua prt_rollups.lua && \
  MAX_EPOCH={{MAX_EPOCH}} lua check_rollups_winner.lua

# run PRT rollups echo test
test-echo:
  just test {{ECHO_DIR}}

# run PRT rollups honeypot test
test-honeypot:
  just test {{HONEYPOT_DIR}}

# read logs from PRT Rollups node, run in separate terminal after `test-echo`
read-node-logs:
  cat dave.log; tail -f dave.log
