[package]
name = "cartesi-prt-core"
description = "A Cartesi validator reference implementation"

version = { workspace = true}
authors = { workspace = true}
edition = { workspace = true}
homepage = { workspace = true}
license-file = { workspace = true}
readme = { workspace = true}
repository = { workspace = true}

[dependencies]
# common-rs
cartesi-dave-arithmetic = { workspace = true }
cartesi-dave-merkle = { workspace = true }
cartesi-dave-kms = { workspace = true }

# machine bindings
cartesi-machine = { workspace = true }

# solidity bindings
cartesi-prt-contracts = { workspace = true }

alloy = { workspace = true, features = ["sol-types", "contract", "network", "reqwest", "signers", "signer-local"] }
ruint = { workspace = true, features = ["num-traits"] }

# async
async-recursion = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["full"] }

anyhow = { workspace = true }
thiserror = { workspace = true }


clap = { workspace = true, features = ["derive", "env"] }
hex = { workspace = true }
log = { workspace = true }
num-traits = { workspace = true }

lazy_static = { workspace = true }
rusqlite = { workspace = true }
rusqlite_migration = { workspace = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
