#!/bin/bash
PATH=/bin:/usr/bin:/sbin:/usr/sbin
export PATH
ls -lR /dev
mount -t proc proc /proc
date -s "2023-12-02 00:00:00"
mkfs.ext2 /dev/pmem1
mkdir -p /dev/tmp
mount -t tmpfs tmpfs /dev/tmp 
ls -lR /dev/tmp
mkdir -p /dev/tmp/mnt
mount /dev/pmem1 /dev/tmp/mnt
cat /proc/mounts
tar --one-file-system -pcf - / | tar -C /dev/tmp/mnt/ -xf -
umount /dev/tmp/mnt
sync

