services:
  dave:
    image: dave:dev
    container_name: dave-node
    command: ["just", "-f", "./prt/tests/rollups/justfile", "test-echo"]
    environment:
      ANVIL_IP_ADDR: 0.0.0.0
    ports:
      - 8545:8545

  sourcify:
    image: sourcify:devel
    ports:
      - 5555:5555
    container_name: sourcify-devel
    environment:
      NODE_ENV: "development"
      NODE_CONFIG_ENV: "devel"
    volumes:
      - sourcify-data:/tmp/sourcify/repository
    depends_on:
      dave:
        condition: service_started

  otterscan:
    image: otterscan/otterscan:v2.8.0
    container_name: otterscan
    ports:
      - 5100:80
    environment:
      - 'OTTERSCAN_CONFIG={"erigonURL": "http://localhost:8545",
        "experimental": false, "branding": {
        "siteName": "Dave Otterscan", "networkTitle": "Dev Network" },
        "sourcify": {
        "sources": {
        "Local Sourcify Repo": {
        "url": "http://localhost:5555/repository",
        "backendFormat": "RepositoryV1"
        },
        "Sourcify Servers": {
        "url": "https://repo.sourcify.dev",
        "backendFormat": "RepositoryV1"
        }}}}'
    depends_on:
      dave:
        condition: service_started

volumes:
  sourcify-data:
