[package]
name = "rollups-blockchain-reader"
version = { workspace = true }

authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license-file = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[dependencies]
rollups-state-manager = { workspace = true }
alloy = { workspace = true }
alloy-rpc-types-eth = "0.2.1"
async-recursion = { workspace = true }
cartesi-dave-contracts = { workspace = true }
cartesi-rollups-contracts = { workspace = true }
clap = { workspace = true }
clap_derive = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
