name: setup-tools
description: Install base tools
inputs:
  target:
    description: 'Architecture to build for (if Rust is setup)'
    required: false
    default: 'x86_64-unknown-linux-gnu'
  rust-version:
    description: 'Rust version to install (if Rust is setup)'
    required: false
    default: '1.86'
  foundry-version:
    description: 'Foundry version to install'
    required: false
    default: 'v1.5.0'
  setup-qemu:
    description: 'Whether to setup QEMU for riscv support'
    required: false
    default: 'true'
  setup-rust:
    description: 'Whether to setup Rust'
    required: false
    default: 'true'
outputs:
  installed-foundry-version:
    description: 'The version of Foundry that was installed'
    value: ${{ steps.set-foundry-version.outputs.version }}
runs:
  using: composite
  steps:
    - name: Set up QEMU for riscv support
      uses: docker/setup-qemu-action@v3
      if: ${{ inputs.setup-qemu == 'true' }}

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      if: ${{ inputs.setup-rust == 'true' }}
      with:
        components: rustfmt
        target: ${{ inputs.target }}
        toolchain: ${{ inputs.rust-version }}
        cache-on-failure: false
        cache-bin: false

    - name: Set Foundry version
      id: set-foundry-version
      shell: bash
      run: |
        echo "version=${{ inputs.foundry-version }}" >> $GITHUB_OUTPUT

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: ${{ steps.set-foundry-version.outputs.version }}

    - name: Install just
      uses: extractions/setup-just@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: 'prt/contracts/package.json'

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
        cache-dependency-path: 'prt/contracts/pnpm-lock.yaml'
