name: setup-tools
description: Install base tools
inputs:
  target:
    description: 'Architecture to build for (if Rust is setup)'
    required: false
    default: 'x86_64-unknown-linux-gnu'
  rust-version:
    description: 'Rust version to install (if Rust is setup)'
    required: false
    default: '1.86'
  foundry-version:
    description: 'Foundry version to install'
    required: false
    default: 'v1.4.3'
  setup-qemu:
    description: 'Whether to setup QEMU for riscv support'
    required: false
    default: 'true'
  setup-rust:
    description: 'Whether to setup Rust'
    required: false
    default: 'true'
outputs:
  installed-foundry-version:
    description: 'The version of Foundry that was installed'
    value: ${{ steps.set-foundry-version.outputs.version }}
runs:
  using: composite
  steps:
    - name: Set up QEMU for riscv support
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
      if: ${{ inputs.setup-qemu == 'true' }}

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
      if: ${{ inputs.setup-rust == 'true' }}
      with:
        components: rustfmt
        target: ${{ inputs.target }}
        toolchain: ${{ inputs.rust-version }}
        cache-on-failure: false
        cache-bin: false

    - name: Set Foundry version
      id: set-foundry-version
      shell: bash
      run: |
        echo "version=${{ inputs.foundry-version }}" >> $GITHUB_OUTPUT

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1.8.0
      with:
        version: ${{ steps.set-foundry-version.outputs.version }}

    - name: Install just
      uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
