name: setup-tools
description: Install base tools
inputs:
  target:
    description: 'Architecture to build for'
    required: false
    default: 'x86_64-unknown-linux-gnu'
  rust_version:
    description: 'Rust version to install'
    required: false
    default: '1.86'
  foundry_version:
    description: 'Foundry version to install'
    required: false
    default: 'v1.4.4'
outputs:
  foundry-version:
    description: 'The version of Foundry that was installed'
    value: ${{ steps.set-foundry-version.outputs.foundry-version }}
runs:
  using: composite
  steps:
    - name: Set up QEMU for riscv support
      uses: docker/setup-qemu-action@v3

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt
        target: ${{ inputs.target }}
        toolchain: ${{ inputs.rust_version }}
        cache-on-failure: false
        cache-bin: false

    - name: Set Foundry version
      id: set-foundry-version
      shell: bash
      run: |
        echo "foundry-version=${{ inputs.foundry_version }}" >> $GITHUB_OUTPUT

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: ${{ steps.set-foundry-version.outputs.foundry-version }}

    - name: Install just
      uses: extractions/setup-just@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: 'prt/contracts/package.json'

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
        cache-dependency-path: 'prt/contracts/pnpm-lock.yaml'
