[package]
name = "cartesi-machine"
version = { workspace = true }
edition = { workspace = true }

authors = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
license-file = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }


[features]
# Links against `libcartesi_jsonrpc.a`
remote_machine = ["cartesi-machine-sys/remote_machine"]

# Downloads from emulator's GitHub release
download_uarch = ["cartesi-machine-sys/download_uarch"]

# requires docker daemon to be running
build_uarch = ["cartesi-machine-sys/build_uarch"]

# requires setting env vars UARCH_PRISTINE_HASH_PATH and UARCH_PRISTINE_RAM_PATH
copy_uarch = ["cartesi-machine-sys/copy_uarch"]

# requires setting env vars LIBCARTESI_PATH and INCLUDECARTESI_PATH
external_cartesi = ["cartesi-machine-sys/external_cartesi"]


[dependencies]
cartesi-machine-sys = { path = "../cartesi-machine-sys" }

base64 = "0.22"
derive_builder = "0.20"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"

[dev-dependencies]
tempfile = "3.16"
