[package]
name = "cartesi-machine"
version = { workspace = true }
edition = { workspace = true }

authors = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
license-file = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }


[features]
remote_machine = ["cartesi-machine-sys/remote_machine"]

[dependencies]
cartesi-machine-sys = { path = "../cartesi-machine-sys" }

base64 = "0.22"
derive_builder = "0.20"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"

[dev-dependencies]
tempfile = "3.16"
